from geneformer import EmbExtractor
import time

# initiate EmbExtractor
t1 = time.time()
embex = EmbExtractor(
                     emb_mode='gene',
                     forward_batch_size=20,
                     nproc=16
)

# extracts embedding from input data
# input data is tokenized rank value encodings generated by Geneformer tokenizer (see tokenizing_scRNAseq_data.ipynb)
# example dataset: https://huggingface.co/datasets/ctheodoris/Genecorpus-30M/tree/main/example_input_files/cell_classification/disease_classification/human_dcm_hcm_nf.dataset

# pip install tdigest

embs = embex.extract_embs("./",
                          "./data/datasets/immune_all_human.dataset/",
                          "./humanpbmc/",
                          "output_prefix")


t2 = time.time()
print(t2 - t1)
import resource
print(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss  / (1e6) )
import torch
print(torch.cuda.max_memory_allocated()/1024/1024/1024)



embs.to_csv("immune_all_human.csv")