from geneformer import EmbExtractor
import time

# initiate EmbExtractor
embex = EmbExtractor(model_type="CellClassifier",
                     num_classes=0,
                     max_ncells=None,
                     emb_layer=0,
                     emb_label=["celltype"],
                     forward_batch_size=200,
                     nproc=16)


# extracts embedding from input data
# input data is tokenized rank value encodings generated by Geneformer tokenizer (see tokenizing_scRNAseq_data.ipynb)
# example dataset: https://huggingface.co/datasets/ctheodoris/Genecorpus-30M/tree/main/example_input_files/cell_classification/disease_classification/human_dcm_hcm_nf.dataset
embs = embex.extract_embs("./",
                          "./humanpbmc.dataset/",
                          "./",
                          "output_prefix")


import scanpy as sc

adata = sc.read_h5ad("../scGPT/examples/HumanPBMC_raw.h5ad")

del embs['celltype']

adata.obsm['X_geneformer'] = embs.values

adata.write_h5ad("./HumanPBMC_geneformer.h5ad")







